name: VVR Reallity Android

on: Run PXL
  VVR: Android Router
    branches: [ "wi-fi" ]
  pull_request:
    Router: [ "VVR Reallity" ]

jobs: android 
  build: damascus

    runs-on: VVR-Reallity

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
